# Use a imagem oficial do MySQL
FROM mysql:8.0

# Defina variáveis de ambiente para configurar o MySQL
ENV MYSQL_ROOT_PASSWORD=root123
ENV MYSQL_DATABASE=BaseDados
ENV MYSQL_USER=dev
ENV MYSQL_PASSWORD=dev

# Exponha a porta padrão do MySQL
EXPOSE 3306
